### ISSUE TITLE
赞一个！

### ISSUE THREAD

**Issue by hyingreborn** [nanmu42/gzip#1]
必须要赞一个！Gin，Echo的中间件感觉各种考虑不完善，其他语言的web框架基本上标配的功能，Go语言里居然找不到一个完全没问题的。

Gin的gzip长期没人维护，新功能只能手动拉代码到本地，搞个排除文件扩展名和路径的配置，配也不是，不配也不是...
Echo的gzip就是默认所有文档都开启压缩，自己想配个Skipper，结果搞了半天获取不到header里的值(可能是我太菜...)

总之这个就很好，真正的开箱即用，菜鸟福音，请求/响应的文档类型都有识别，哪些文档类型该不该压缩，多大的文件需要压缩，这本来不就是一个gzip库该去识别的吗...

希望作者继续维护下去~

用的有个疑问：
1、gzip.NewHandler(gzip.Config{})似乎必须要传入所有参数，仅传入CompressionLevel会报
```
invalid MinContentLength: 0
```
2、使用MinContentLength来判断文档大小，是否可以改为按照文档size来识别？比如配置文档大于4kb才开启gzip

**Comment by nanmu42** [comment]
> 1、gzip.NewHandler(gzip.Config{})似乎必须要传入所有参数，仅传入CompressionLevel会报
> 
> invalid MinContentLength: 0

使用`gzip.DefaultHandler()`可以创建一个开箱即用的压缩实例，如果需要自己定义Config，可以参考[这里的默认配置](https://github.com/nanmu42/gzip/blob/b7f5fb352e7bc9318527318a658d31d9fa02661f/handler.go#L86-L97)。

>  2、使用MinContentLength来判断文档大小，是否可以改为按照文档size来识别？比如配置文档大于4kb才开启gzip

`MinContentLength`定义了启用gzip的阈值，单位为字节，将它设为`4 * 1024`（4KB）可以满足你的需求。

感谢你的肯定和支持。 :beer:

**Comment by nanmu42** [comment]
如果还有问题，欢迎重启这个Issue.
