### ISSUE TITLE
Compression doesn't work for large responces

### ISSUE THREAD

**Issue by dmitrydvm** [nanmu42/gzip#22]
Hello.
My api gives different response sizes. Where the response is small (13kb) compression works fine and returns 1.78kb. But if the size is large (2.75mb), then the response is returned uncompressed, although the Content-Encoding:gzip header is added. I also see that for large responses, the Transfer-Encoding:chunked header is returned, but no Content-Length is returned.
What should be done to compress all responses?
Compressed:
![image](https://user-images.githubusercontent.com/3179176/163337403-cff25e26-48d5-40d2-bda8-6562a743d279.png)

Not compressed:
![image](https://user-images.githubusercontent.com/3179176/163337486-59a96730-f3c9-4bde-87a4-127d39d91d07.png)

**Comment by nanmu42** [comment]
Hello,

Under both scenarios the responses are compressed in streaming way. For large response, Go's official http package uses chunk mode to write response and content length is not available by its design.

Postman does decompression automatically for you so it seems responses are not compressed.

To be sure, check Postman console for connection detail or inspect requests in Chrome DevTools network panel, where you should see both compressed size and decompressed size of responses.

**Comment by dmitrydvm** [comment]
Indeed, you are right. Thanks for the explanation. Postman misled me because on a small response shows a compressed size.
![image](https://user-images.githubusercontent.com/3179176/163424878-8dc0fd27-4f7e-4189-a0e8-79833627f120.png)

**Comment by nanmu42** [comment]
Glad to help. :)
