### ISSUE TITLE
请教：在gzip中间件的基础上，如何再加个加密中间件？

### ISSUE THREAD

**Issue by bagualing** [nanmu42/gzip#27]
中间件新手，纯来请教。

我的Respond body根据业务有时要把整个body全部加密，所以希望写一个加密处理的中间件，来统一处理加密需求。
业务handler处理完后，会设置一个Head值来标记body是否要加密，如果要加密，就由这个加密中间件来完成加密。最后由gzip中间件根据加密后body的大小来决定是否压缩。

请教这个加密中间件的RespondWriter应该如何来写？主要是原gin  respondwriter已被gzip的writer接管了，所以不知道如何来写这个加密的了。特来请教，谢谢！

**Comment by nanmu42** [comment]
如果我没记错，gzip这边在wrap了response writer后，产出的东西也是满足gin或者http的interface的，你可以基于interface继续wrap.

一般的pattern是一个结构体把interface作为自己的field，然后结构体本身依然满足这个interface.

这样中间件可以一个又叠一个。

**Comment by nanmu42** [comment]
考虑到你要加密body，gzip必须包在你加密的中间件的外面，否则客户端没法正确工作。

实现时可以先完全去掉gzip，实现完加密后再考虑加回来。
密文未必有较好的压缩比，另外gzip默认好像会挑content type，这些都要考虑。

**Comment by bagualing** [comment]
是的，压缩放在最外层。
我再看看其它类似中间件是如何处理的。
